### PR TITLE
Added esp32s2 driver

### PR DESCRIPTION
**Pull request by jakub-kocka**
- changed workflow for signing the drivers to universal usage
- added esp32s2 driver
- split driver for FT2232H chip to `esp-wrover-kit` and `esp32-s2-kaluga`

### CODE REVIEW

**Review by dobairoland — APPROVED** [review]
LGTM, but where those inputs come from? I think we would need to document how and with parameters should one start workflows.

**Comment by igrr** [comment]
> with ESP32-WROVER-B - not tested with ESP32-WROVER-E

This should not make a difference, the way the FT2232H is wired up is identical. 

I think `esp-wrover-kit` and `esp32-s2-kaluga` names could work, as they are very close to the board product names.

**Comment by jakub-kocka** [comment]
> I think `esp-wrover-kit` and `esp32-s2-kaluga` names could work, as they are very close to the board product names.

OK, so we will have two releases for the dev boards and universal driver source files targeting the FT2232H. Could this be the solution?

**Comment by tore-espressif** [comment]
@jakub-kocka could you please also update https://github.com/espressif/esp-win-usb-drivers/blob/master/CHANGELOG.md ?

**Comment by jakub-kocka** [comment]
Thank you guys for the reviews!

I have updated `README.md` to make clear the process of using the workflow for driver release, @dobairoland.

Also, I have updated the `CHANGELOG.md` with the driver releases (corresponding to the actual date of creation and the date that will be displayed in the driver manager), @tore-espressif.

And I have changed the names of the drivers, @igrr. I have decided to go for the "duplicated" source files because of the `Original name` which will be displayed with the driver. In my opinion, if we display it such as `FT2232H` it can get a bit confusing for the users later when they forget about the installation.

This is what I mean:

    Published Name:     oem14.inf
    Original Name:      esp-wrover-kit.inf
    Provider Name:      Espressif
    Class Name:         USBDevice
    Class GUID:         {88bae032-5a81-49f0-bc3d-a4ff138216d6}
    Driver Version:     07/01/2024 1.0.0.0
    Signer Name:        Espressif Systems (Shanghai) Co., Ltd.
    
The [releases](https://github.com/espressif/esp-win-usb-drivers/releases) have been prepared as drafts.

**Comment by dobairoland** [comment]
LGTM. Thanks.

**Comment by jakub-kocka** [comment]
Are you OK with the changes @igrr, @tore-espressif?

**Review by igrr — APPROVED** [review]

**Comment by jakub-kocka** [comment]
Thank you guys for the reviews!

I am merging this and will release the driver archives.

**Pull request merged**
